name: Publish to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  build-and-publish:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      - uses: actions/checkout@v2

      - uses: meitar/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
          gh_pages_publishing_source: master
